### ISSUE TITLE
Use absl::string_view for string arguments

### ISSUE THREAD

**Issue by smolkaj** [googleinterns/p4-symbolic#22]
For example in https://github.com/googleinterns/p4-symbolic/pull/17.

**Comment by KinanBab** [comment]
Tip of the week https://abseil.io/tips/1 mentions that std::string_view is preferrable for c++17 projects.

We are still using C++11, so I am going to absl::string_view for now. I opened an issue for c++17

**Comment by KinanBab** [comment]
Actually ended up using const char * instead.

"Adding string_view into an existing codebase is not always the right answer: changing parameters to pass by string_view can be inefficient if those are then passed to a function requiring a string or a NUL-terminated const char*. It is best to adopt string_view starting at the utility code and working upward, or with complete consistency when starting a new project."

Our code relies on pdpi::ReadProtoFromFile and <ifstream>.open that take std::string and const char *. Using string_view will be annoying and inefficient and will require several copies.

Also, using std::string will be annoying since the data will be copied twice (argv -> std::string -> .c_str() for ifstream).

**Comment by smolkaj** [comment]
Totally agree, thanks for looking into it.
